### PR TITLE
🐛 Fix scorecard-action e2e test breakages

### LINKED ISSUE #116: API returning 500 responses
Not sure if I've got the correct repository so please feel free to transfer or let me know the right repo to report this.

Over at Shields.io we consume a scorecard api at https://api.securityscorecards.dev/projects/:host/:org/:repo. At some point over the last few weeks this endpoint started returning a 500 response for repositories that haven't enabled the service/haven't been scanned, and response also includes an error "error pulling from GCS bucket"

```
$ curl -i https://api.securityscorecards.dev/projects/github.com/badges/shields
HTTP/2 500 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
x-cloud-trace-context: 08b36f664a2e6adfd3e39e0fefbe9e58;o=1
date: Sun, 12 Jun 2022 23:57:21 GMT
server: Google Frontend
content-length: 30

error pulling from GCS bucket
```

Whereas this was previously returning a typical/expected 404 response code (more background in https://github.com/badges/shields/pull/7687#issuecomment-1091871943). The API still works fine for repositories that have been enabled/scanned

### PR DESCRIPTION
**Pull request by azeemshaikh38**
Fixes e2e test failures in scorecard-action:

- e2e tests use steps which are different from the prod steps, so added an exception for them. Fixes ossf/scorecard-action#455, fixes ossf/scorecard-action#456, fixes ossf/scorecard-action#457, fixes ossf/scorecard-action#458, fixes ossf/scorecard-action#459, fixes ossf/scorecard-action#460
- Improve http error handling. Fixes  #116.

### CODE REVIEW

File: app/errors.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+var (
+	errNotFound = errors.New("not found")
+	// TODO: Add errors corresponding to http status codes
+	// that should be returned by the server.
+)
+
+func errHandler(w http.ResponseWriter, err error) {
+	if errors.Is(err, errNotFound) {
+		log.Printf("%v", err)
```
Comment (laurentsimon) [inline app/errors.go:31]: log is intended?

**Review by laurentsimon — APPROVED** [review]

File: app/errors.go (hunk 1 above)
Comment (azeemshaikh38) [reply app/errors.go:29]: Yeah this is for internal debugging (server-side).
