### PR TITLE
Fix default branch verification

### LINKED ISSUE #554: Default branch verification fails when reusable workflow repository has different branch
## Problem Description

Although reusable workflows are [now supported](https://github.com/ossf/scorecard-webapp/issues/300), when using the Scorecard Action I hit an edge case at the [branch verification stage](https://github.com/ossf/scorecard-webapp/blob/main/app/server/post_results.go#L205-L209) when the repository hosting the reusable workflow file has a different default branch (in our case, `develop`) than the repository calling the workflow (`main`).

Example showing workflow verification failure on the calling workflow: https://github.com/cisco-ospo/sample-project/actions/runs/7719025635/job/21041490540#step:4:1294

To test this, I [temporarily swapped](https://github.com/cisco-ospo/.github/pull/77/files) the default branch from `develop` to `main` on the reusable workflow host repository, then successfully reran the above workflow: https://github.com/cisco-ospo/sample-project/actions/runs/7719144312/job/21041843243#step:4:1293

## Steps to Reproduce

1. Create repository with a default branch of `dev` or `develop`
2. Create a [reusable workflow file](https://github.com/cisco-ospo/.github/blob/main/.github/workflows/_scorecard.yml) for the Scorecard Action
3. Create repository with a default branch name of `main`
4. Create a workflow file which [calls the reusable workflow](https://github.com/cisco-ospo/sample-project/blob/main/.github/workflows/scorecard.yml#L23) from Step 2
5. Run the Scorecard workflow with `publish_results` set to `true`

Let me know if any other details would be of use!

### PR DESCRIPTION
**Pull request by ppkarwasz**
In case the Scorecard action is used in a reusable GitHub workflow, the repository of the workflow can be different from the repository of the project being analyzed.

Currently, the server checks that the branch for which the Scorecard is computed is the default branch of the repository containing the **reusable** workflow.

This PR modifies the verification procedure to use the repository of the **calling** workflow instead.

Closes #554

### CODE REVIEW

**Comment by spencerschrock** [comment]
It's been a minute since I've touched this code, so let me walk through my thoughts looking at the whole cert for your workflow example in the linked issue.

https://search.sigstore.dev/?logIndex=195916436
```
  Subject Alternative Name (critical):
    url:
    - https://github.com/apache/logging-parent/.github/workflows/scorecards-analysis-reusable.yaml@refs/heads/main
  OIDC Issuer: https://token.actions.githubusercontent.com
  GitHub Workflow Trigger: push
  GitHub Workflow SHA: 4412d1b17c31dcac30de0a0c4baa61cc0394b8f6
  GitHub Workflow Name: scorecards-analysis
  GitHub Workflow Repository: ppkarwasz/logging-log4j2
  GitHub Workflow Ref: refs/heads/github-actions
  OIDC Issuer (v2): https://token.actions.githubusercontent.com
  Build Signer URI: https://github.com/apache/logging-parent/.github/workflows/scorecards-analysis-reusable.yaml@refs/heads/main
  Build Signer Digest: 4551dd76ab5869821ff9d0242e3171e10c3d1875
  Runner Environment: github-hosted
  Source Repository URI: https://github.com/ppkarwasz/logging-log4j2
  Source Repository Digest: 4412d1b17c31dcac30de0a0c4baa61cc0394b8f6
  Source Repository Ref: refs/heads/github-actions
  Source Repository Identifier: '447390126'
  Source Repository Owner URI: https://github.com/ppkarwasz
  Source Repository Owner Identifier: '12533274'
  Build Config URI: https://github.com/ppkarwasz/logging-log4j2/.github/workflows/scorecards-analysis.yaml@refs/heads/github-actions
  Build Config Digest: 4412d1b17c31dcac30de0a0c4baa61cc0394b8f6
  Build Trigger: push
  Run Invocation URI: https://github.com/ppkarwasz/logging-log4j2/actions/runs/14422941913/attempts/1
  Source Repository Visibility At Signing: public
```

In terms of what goes where in `extractCertInfo`

```
type certInfo struct {
	repoFullName  string // 1.3.6.1.4.1.57264.1.5 | Github Workflow Repository
	repoBranchRef string // 1.3.6.1.4.1.57264.1.6 | Github Workflow Ref
	repoSHA       string // 1.3.6.1.4.1.57264.1.3 | Github Workflow SHA
	workflowPath  string // derived from URI
	workflowRef   string
}
```

So `repoFullName` "contains the repository that the workflow run was based upon" ([link](https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md#1361415726415--github-workflow-repository-deprecated)), which is the top-level repo which calls the reusable workflow,`ppkarwasz/logging-log4j2`, and what we want.

In terms of fetching the workflow now have workflow path and ref based on the URI:
```
https://github.com/apache/logging-parent/.github/workflows/scorecards-analysis-reusable.yaml@refs/heads/main
```

Since this is a re-usable workflow we hit this edge case and end up using the `@refs/heads/main` part:
https://github.com/ossf/scorecard-webapp/blob/613af5f9fdebd917f7fc91af1a86dcd72df498d9/app/server/post_results.go#L212-L217

Ideally we would use tie this to the commit in question instead of `main`, https://github.com/apache/logging-parent/commit/4551dd76ab5869821ff9d0242e3171e10c3d1875, which we have available as `Build Signer Digest: 4551dd76ab5869821ff9d0242e3171e10c3d1875`.

**Comment by spencerschrock** [comment]
I'm following up with some colleagues regarding these assumptions, but assuming this gets merged you'll be able to test this against the staging instance and then I can push the change to prod after that.

File: app/server/post_results_test.go [hunk 1]
```diff
@@ -219,6 +219,48 @@ func FuzzExtractCertInfo(f *testing.F) {
...
+			path: "malformed",
+			want: results{
+				org:  "",
+				repo: "",
+				ok:   false,
+			},
+		},
+	}
+	for _, tt := range tests {
+		tt := tt
```
Comment (spencerschrock) [inline app/server/post_results_test.go:253]: just deleting `tt := tt` should be enough to make the linter happy

**Review by spencerschrock — APPROVED** [review]
The change looks good to me. I think my comment about using `Build Config Digest` is out of scope for this PR

**Comment by ppkarwasz** [comment]
> I'm following up with some colleagues regarding these assumptions, but assuming this gets merged you'll be able to test this against the staging instance and then I can push the change to prod after that.

Thanks. How can I use the staging instance?

**Comment by spencerschrock** [comment]
> Thanks. How can I use the staging instance?

like this. Which would require changes to the reusable workflow. I've copy/pasted the workflow into my test repo, with the PAT token removed and the staging server specified:
https://github.com/spencerschrock/actions-test/blob/05f650376f71520c3aa9db97bfb480d673e9f559/.github/workflows/scorecard_reusable.yml#L23

**Comment by spencerschrock** [comment]
It will need some time to deploy to staging, will comment again when it's live

**Comment by ppkarwasz** [comment]
Thanks!

**Comment by spencerschrock** [comment]
Should be live in staging

**Comment by spencerschrock** [comment]
I'll take a look at deploying to prod early next week.
